name: OKRADISH
description: "A comprehensive diet monitoring app that provides detailed statistics on nutrient intake"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localization: ^0.1.12
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^1.1.6
  parse_server_sdk_flutter: ^8.0.0
  flutter_blue_plus: ^1.32.11
  get: ^4.6.6
  fl_chart: ^0.68.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.4
  video_player: ^2.9.1
  persian_datetime_picker: ^3.1.0
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen: ^5.6.0
  flutter_gen_runner:
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/icon.png"
  web:
    generate: true
    image_path: "assets/png/icon.png"
    background_color: "#FFFFFF"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/png/icon.png"
  adaptive_icon_foreground_inset: 24

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/png/icon.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/png/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/video/















  fonts:
    - family: estedad
      fonts:
        - asset: assets/fonts/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900






  #


