import 'package:OKRADISH/model/food.dart';

List<Food> mainfood = [
  Food(id: '1', name: 'پلو کته(بدون روغن)', carboPerGram: 21, proteinPerGram: 2, fatPerGram: 0.2, fibersPerGram: 1),
  Food(id: '2', name: 'پلو کته(با روغن)', carboPerGram: 21, proteinPerGram: 2, fatPerGram: 4.7, fibersPerGram: 1),
  Food(id: '3', name: 'پلو آبکش(بدون روغن)', carboPerGram: 28, proteinPerGram: 2.3, fatPerGram: 0.2, fibersPerGram: 0.3),
  Food(id: '4', name: 'پلو آبکش(با روغن)', carboPerGram: 28, proteinPerGram: 2.3, fatPerGram: 4.7, fibersPerGram: 0.3),
  Food(id: '5', name: 'زرشک پلو', carboPerGram: 28, proteinPerGram: 2.2, fatPerGram: 6.4, fibersPerGram: 0.5),
  Food(id: '6', name: 'میگوپلو', carboPerGram: 25, proteinPerGram: 6.5, fatPerGram: 6.5, fibersPerGram: 0.7),
  Food(id: '7', name: 'استانبولی پلو', carboPerGram: 33.4, proteinPerGram: 3.1, fatPerGram: 3.2, fibersPerGram: 1.1),
  Food(id: '8', name: 'عدس پلو', carboPerGram: 31, proteinPerGram: 4.5, fatPerGram: 4.6, fibersPerGram: 2.5),
  Food(id: '9', name: 'هویچ پلو', carboPerGram: 30.5, proteinPerGram: 2.4, fatPerGram: 5, fibersPerGram: 1.4),
  Food(id: '10', name: 'سبزی پلو', carboPerGram: 32, proteinPerGram: 3.2, fatPerGram: 4.5, fibersPerGram: 0.8),
  Food(id: '11', name: 'باقلا پلو', carboPerGram: 37.3, proteinPerGram: 4.5, fatPerGram: 4.3, fibersPerGram: 1.7),
  Food(id: '12', name: 'ته چین مرغ', carboPerGram: 21.3, proteinPerGram: 9.9, fatPerGram: 7.9, fibersPerGram: 1),
  Food(id: '13', name: 'قیمه پلو', carboPerGram: 30, proteinPerGram: 7.1, fatPerGram: 9.3, fibersPerGram: 1.7),
  Food(id: '14', name: 'لوبیاپلو بدون گوشت', carboPerGram: 23.4, proteinPerGram: 2.3, fatPerGram: 5.8, fibersPerGram: 1.3),
  Food(id: '15', name: 'قنبرپلو', carboPerGram: 26.6, proteinPerGram: 7.5, fatPerGram: 6, fibersPerGram: 0.7),
  Food(id: '16', name: 'آلبالوپلو', carboPerGram: 31.3, proteinPerGram: 2.4, fatPerGram: 5.1, fibersPerGram: 0.8),
  Food(id: '17', name: 'ماهی سالمون پخته', carboPerGram: 0, proteinPerGram: 27.3, fatPerGram: 7.5, fibersPerGram: 0),
  Food(id: '18', name: 'ماهی سالمون سرخ شده', carboPerGram: 0, proteinPerGram: 25.7, fatPerGram: 13.3, fibersPerGram: 0),
  Food(id: '19', name: 'ماهی سفید پخته', carboPerGram: 0, proteinPerGram: 23.5, fatPerGram: 1.6, fibersPerGram: 0),
  Food(id: '20', name: 'ماهی سفید سرخ شده', carboPerGram: 0, proteinPerGram: 19, fatPerGram: 8.1, fibersPerGram: 0),
  Food(id: '21', name: 'سینه مرغ پخته', carboPerGram: 0, proteinPerGram: 29, fatPerGram: 3, fibersPerGram: 0),
  Food(id: '22', name: 'سینه مرغ سرخ شده', carboPerGram: 0, proteinPerGram: 24.8, fatPerGram: 13.2, fibersPerGram: 0),
  Food(id: '23', name: 'ران مرغ پخته', carboPerGram: 0, proteinPerGram: 25, fatPerGram: 9.7, fibersPerGram: 0),
  Food(id: '24', name: 'ران مرغ سرخ شده', carboPerGram: 1.2, proteinPerGram: 28, fatPerGram: 10.3, fibersPerGram: 0),
  Food(id: '25', name: 'بال مرغ پخته', carboPerGram: 0, proteinPerGram: 27, fatPerGram: 7.1, fibersPerGram: 0),
  Food(id: '26', name: 'بال مرغ سرخ شده', carboPerGram: 0, proteinPerGram: 30, fatPerGram: 9.1, fibersPerGram: 0),
  Food(id: '27', name: 'شنیسل مرغ', carboPerGram: 16, proteinPerGram: 18, fatPerGram: 18, fibersPerGram: 1.3),
  Food(id: '28', name: 'برگر مرغ', carboPerGram: 1, proteinPerGram: 19.6, fatPerGram: 7.1, fibersPerGram: 1),
  Food(id: '29', name: 'کالباس مرغ', carboPerGram: 4.3, proteinPerGram: 20, fatPerGram: 1.5, fibersPerGram: 0),
  Food(id: '30', name: 'استیک مرغ', carboPerGram: 7.6, proteinPerGram: 24, fatPerGram: 15, fibersPerGram: 0.3),
  Food(id: '31', name: 'ناگت مرغ', carboPerGram: 14, proteinPerGram: 15, fatPerGram: 20, fibersPerGram: 2.1),
  Food(id: '32', name: 'تخم مرغ پخته', carboPerGram: 1.1, proteinPerGram: 13, fatPerGram: 11, fibersPerGram: 0),
  Food(id: '33', name: 'نیمرو', carboPerGram: 0.8, proteinPerGram: 13.6, fatPerGram: 14.8, fibersPerGram: 0),
  Food(id: '34', name: 'املت تخم مرغ', carboPerGram: 0.6, proteinPerGram: 10.5, fatPerGram: 11.6, fibersPerGram: 0),
  Food(id: '35', name: 'کالباس گوشت', carboPerGram: 2.4, proteinPerGram: 11, fatPerGram: 29.1, fibersPerGram: 0),
  Food(id: '36', name: 'کالباس مرغ', carboPerGram: 4.3, proteinPerGram: 20, fatPerGram: 1.5, fibersPerGram: 0),
  Food(id: '37', name: 'کباب کوبیده', carboPerGram: 2.5, proteinPerGram: 19.8, fatPerGram: 15.5, fibersPerGram: 0.4),
  Food(id: '38', name: 'کباب برگ', carboPerGram: 0, proteinPerGram: 22.5, fatPerGram: 23.5, fibersPerGram: 0),
  Food(id: '39', name: 'جوجه کباب', carboPerGram: 3.7, proteinPerGram: 26.5, fatPerGram: 9.8, fibersPerGram: 0.8),
  Food(id: '40', name: 'آبگوشت', carboPerGram: 18.6, proteinPerGram: 9.6, fatPerGram: 6, fibersPerGram: 2),
  Food(id: '41', name: 'خورشت قرمه سبزی', carboPerGram: 12, proteinPerGram: 10.6, fatPerGram: 13.7, fibersPerGram: 3),
  Food(id: '42', name: 'خورشت هویچ', carboPerGram: 24.8, proteinPerGram: 14.6, fatPerGram: 21, fibersPerGram: 3.8),
  Food(id: '43', name: 'خورشت کرفس', carboPerGram: 6, proteinPerGram: 8.5, fatPerGram: 14.5, fibersPerGram: 1.7),
  Food(id: '44', name: 'خورشت قیمه', carboPerGram: 11.1, proteinPerGram: 7, fatPerGram: 10.2, fibersPerGram: 3.4),
  Food(id: '45', name: 'خورشت فسنجان', carboPerGram: 13.3, proteinPerGram: 12, fatPerGram: 20.7, fibersPerGram: 2.4),
  Food(id: '46', name: 'خورشت بامیه', carboPerGram: 6.7, proteinPerGram: 10.5, fatPerGram: 12, fibersPerGram: 2.9),
  Food(id: '98', name: 'فلافل', carboPerGram: 21.3, proteinPerGram: 6.4, fatPerGram: 5, fibersPerGram: 1.4),
  Food(id: '99', name: 'همبرگر', carboPerGram: 31.5, proteinPerGram: 16.5, fatPerGram: 12, fibersPerGram: 1.2),
  Food(id: '101', name: 'بلال', carboPerGram: 21, proteinPerGram: 3.4, fatPerGram: 1.5, fibersPerGram: 2.4),
  Food(id: '102', name: 'لبو پخته', carboPerGram: 10, proteinPerGram: 1.7, fatPerGram: 0.2, fibersPerGram: 2),
  Food(id: '103', name: 'آبنبات ساده', carboPerGram: 99, proteinPerGram: 0, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '104', name: 'آبنبات میوه‌ای', carboPerGram: 82.7, proteinPerGram: 0.3, fatPerGram: 0.1, fibersPerGram: 1.6),
  Food(id: '105', name: 'ماست و خیار', carboPerGram: 9, proteinPerGram: 6, fatPerGram: 0.3, fibersPerGram: 0.5),
  Food(id: '106', name: 'آب گوشت', carboPerGram: 4.8, proteinPerGram: 3.7, fatPerGram: 2.3, fibersPerGram: 0.4),
  Food(id: '107', name: 'اردک ماهی پخته', carboPerGram: 0, proteinPerGram: 24.5, fatPerGram: 1.5, fibersPerGram: 0),
  Food(id: '108', name: 'جوجه چینی', carboPerGram: 22.6, proteinPerGram: 5.7, fatPerGram: 5, fibersPerGram: 1.9),
  Food(id: '109', name: 'سوسیس بندری', carboPerGram: 8.5, proteinPerGram: 8.7, fatPerGram: 18.1, fibersPerGram: 0.9),
  Food(id: '110', name: 'سوسیس تخم مرغ', carboPerGram: 1.3, proteinPerGram: 14.5, fatPerGram: 21, fibersPerGram: 0.2),
  Food(id: '111', name: 'آش اوماج', carboPerGram: 29.4, proteinPerGram: 6.5, fatPerGram: 2.7, fibersPerGram: 3.4),
  Food(id: '112', name: 'آش دوغ', carboPerGram: 14.8, proteinPerGram: 6.5, fatPerGram: 2.5, fibersPerGram: 1.2),
  Food(id: '113', name: 'آش رشته', carboPerGram: 24.8, proteinPerGram: 7.5, fatPerGram: 5.1, fibersPerGram: 5.2),
  Food(id: '114', name: 'آش کشک', carboPerGram: 25, proteinPerGram: 8, fatPerGram: 3.5, fibersPerGram: 5.1),
  Food(id: '115', name: 'یتیمچه', carboPerGram: 8.5, proteinPerGram: 1.1, fatPerGram: 2.8, fibersPerGram: 1.5),
  Food(id: '116', name: 'سالاد ماکارونی', carboPerGram: 17.5, proteinPerGram: 5.8, fatPerGram: 8.2, fibersPerGram: 2.1),
  Food(id: '117', name: 'آش بلغور', carboPerGram: 19.7, proteinPerGram: 5.3, fatPerGram: 2.7, fibersPerGram: 5.5),
  Food(id: '118', name: 'لازانیا پنیر', carboPerGram: 14, proteinPerGram: 7, fatPerGram: 5, fibersPerGram: 1.7),
  Food(id: '119', name: 'لازانیا گوشت', carboPerGram: 15, proteinPerGram: 7, fatPerGram: 4.9, fibersPerGram: 1.7),
  Food(id: '120', name: 'هات داگ', carboPerGram: 50, proteinPerGram: 9, fatPerGram: 4.5, fibersPerGram: 2),
  Food(id: '121', name: 'پیتزا سبزیجات', carboPerGram: 24, proteinPerGram: 9, fatPerGram: 4.3, fibersPerGram: 1.3),
  Food(id: '122', name: 'خورشت کنگر', carboPerGram: 12.9, proteinPerGram: 8.2, fatPerGram: 7.3, fibersPerGram: 9),
  Food(id: '123', name: 'باسلوق', carboPerGram: 65.1, proteinPerGram: 6.1, fatPerGram: 15.2, fibersPerGram: 10.2),
  Food(id: '124', name: 'بامیه', carboPerGram: 29, proteinPerGram: 1.6, fatPerGram: 29, fibersPerGram: 0.4),
  Food(id: '125', name: 'آب دوغ خیار', carboPerGram: 1.4, proteinPerGram: 0.3, fatPerGram: 2.8, fibersPerGram: 0.3),
];
final snack = [
  Food(id: '47', name: 'بیسکوییت ساقه طلایی', carboPerGram: 66.6, proteinPerGram: 6.6, fatPerGram: 23, fibersPerGram: 6.7),
  Food(id: '48', name: 'ماکارونی پخته', carboPerGram: 31, proteinPerGram: 6, fatPerGram: 0.9, fibersPerGram: 1.8),
  Food(id: '49', name: 'نان لواش', carboPerGram: 64, proteinPerGram: 8, fatPerGram: 0.7, fibersPerGram: 2.3),
  Food(id: '50', name: 'نان بربری', carboPerGram: 60, proteinPerGram: 7.6, fatPerGram: 0.5, fibersPerGram: 2.2),
  Food(id: '51', name: 'نان سنگک', carboPerGram: 56.6, proteinPerGram: 7.7, fatPerGram: 0.6, fibersPerGram: 3.6),
  Food(id: '52', name: 'نان باگت', carboPerGram: 58.5, proteinPerGram: 8.4, fatPerGram: 2.4, fibersPerGram: 2.2),
  Food(id: '53', name: 'کره', carboPerGram: 0.1, proteinPerGram: 0.8, fatPerGram: 81, fibersPerGram: 0),
  Food(id: '54', name: 'پنیر سفید', carboPerGram: 2.5, proteinPerGram: 20.3, fatPerGram: 24.3, fibersPerGram: 0),
  Food(id: '55', name: 'پنیر خامه‌ای', carboPerGram: 5.5, proteinPerGram: 6.1, fatPerGram: 34, fibersPerGram: 0),
  Food(id: '56', name: 'مغز گردو', carboPerGram: 14, proteinPerGram: 15, fatPerGram: 65, fibersPerGram: 7),
  Food(id: '57', name: 'مغز پسته نمکی', carboPerGram: 0, proteinPerGram: 0, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '58', name: 'مغز بادام زمینی نمکی', carboPerGram: 0, proteinPerGram: 25.6, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '59', name: 'مغز بادام درختی', carboPerGram: 0, proteinPerGram: 23.7, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '60', name: 'کره بادام زمینی', carboPerGram: 20, proteinPerGram: 25, fatPerGram: 50, fibersPerGram: 6),
  Food(id: '61', name: 'عسل', carboPerGram: 82.5, proteinPerGram: 0.3, fatPerGram: 0, fibersPerGram: 0.2),
  Food(id: '62', name: 'مربا هویچ', carboPerGram: 74, proteinPerGram: 0, fatPerGram: 0, fibersPerGram: 0.7),
  Food(id: '63', name: 'مربا آلبالو', carboPerGram: 67, proteinPerGram: 0.4, fatPerGram: 0, fibersPerGram: 1),
  Food(id: '64', name: 'ماست کم چرب', carboPerGram: 7.6, proteinPerGram: 5.7, fatPerGram: 0.2, fibersPerGram: 0),
  Food(id: '65', name: 'ماست پر چرب', carboPerGram: 4.6, proteinPerGram: 3.4, fatPerGram: 3.2, fibersPerGram: 0),
  Food(id: '66', name: 'خامه', carboPerGram: 3, proteinPerGram: 2.1, fatPerGram: 30.9, fibersPerGram: 0),
  Food(id: '67', name: 'سیب زمینی سرخ کرده', carboPerGram: 41, proteinPerGram: 3.4, fatPerGram: 15, fibersPerGram: 3.8),
  Food(id: '68', name: 'قارچ سوخاری', carboPerGram: 20.3, proteinPerGram: 5, fatPerGram: 9.3, fibersPerGram: 1.6),
  Food(id: '69', name: 'گوشت همبرگر', carboPerGram: 0, proteinPerGram: 25.3, fatPerGram: 16.2, fibersPerGram: 0),
  Food(id: '70', name: 'پیتزا گوشت و قارچ', carboPerGram: 30.7, proteinPerGram: 11.7, fatPerGram: 11.5, fibersPerGram: 2.3),
  Food(id: '71', name: 'پیتزا پپرونی', carboPerGram: 30.5, proteinPerGram: 12, fatPerGram: 14.2, fibersPerGram: 1.8),
  Food(id: '72', name: 'سوپ جو', carboPerGram: 9.6, proteinPerGram: 1.5, fatPerGram: 1.8, fibersPerGram: 2.5),
  Food(id: '73', name: 'سوپ قارچ و خامه', carboPerGram: 4.8, proteinPerGram: 2.5, fatPerGram: 5.8, fibersPerGram: 0.5),
  Food(id: '74', name: 'سویا پخته', carboPerGram: 11, proteinPerGram: 12.3, fatPerGram: 6.4, fibersPerGram: 4.2),
  Food(id: '75', name: 'سویا خام', carboPerGram: 11, proteinPerGram: 13, fatPerGram: 6.8, fibersPerGram: 4.2),
  Food(id: '76', name: 'بادام هندی خام', carboPerGram: 30, proteinPerGram: 18, fatPerGram: 44, fibersPerGram: 3.3),
  Food(id: '77', name: 'تخمه آفتابگردان', carboPerGram: 24, proteinPerGram: 19, fatPerGram: 50, fibersPerGram: 9),
  Food(id: '78', name: 'تخمه کدو', carboPerGram: 15, proteinPerGram: 30, fatPerGram: 49, fibersPerGram: 7),
  Food(id: '79', name: 'سالاد شیرازی', carboPerGram: 3.5, proteinPerGram: 0.9, fatPerGram: 0.2, fibersPerGram: 0.9),
  Food(id: '80', name: 'سالاد سزار با مرغ', carboPerGram: 7.7, proteinPerGram: 8.6, fatPerGram: 5.8, fibersPerGram: 2.4),
  Food(id: '81', name: 'پاستا مرغ', carboPerGram: 20.3, proteinPerGram: 6.2, fatPerGram: 8.7, fibersPerGram: 0),
  Food(id: '82', name: 'سالاد کلم', carboPerGram: 11, proteinPerGram: 1, fatPerGram: 0, fibersPerGram: 1),
  Food(id: '83', name: 'سالاد الویه با مرغ', carboPerGram: 10.1, proteinPerGram: 8.7, fatPerGram: 8.3, fibersPerGram: 1.3),
];
final other = [
  Food(id: '84', name: 'زردآلو', carboPerGram: 83, proteinPerGram: 4.9, fatPerGram: 0.6, fibersPerGram: 8.4),
  Food(id: '85', name: 'هلو', carboPerGram: 83, proteinPerGram: 4.9, fatPerGram: 1, fibersPerGram: 0),
  Food(id: '86', name: 'هندوانه', carboPerGram: 8, proteinPerGram: 0.6, fatPerGram: 0.2, fibersPerGram: 0.4),
  Food(id: '87', name: 'خربزه', carboPerGram: 8.2, proteinPerGram: 0.8, fatPerGram: 0.2, fibersPerGram: 0.9),
  Food(id: '88', name: 'سیب قرمز', carboPerGram: 14.1, proteinPerGram: 0.2, fatPerGram: 0.2, fibersPerGram: 2.3),
  Food(id: '89', name: 'آلبالو خشک', carboPerGram: 78, proteinPerGram: 7.6, fatPerGram: 1.9, fibersPerGram: 10),
  Food(id: '90', name: 'باقلوا', carboPerGram: 58, proteinPerGram: 3.3, fatPerGram: 25, fibersPerGram: 1.7),
  Food(id: '91', name: 'ارده', carboPerGram: 21, proteinPerGram: 17, fatPerGram: 54, fibersPerGram: 9),
  Food(id: '92', name: 'ژله', carboPerGram: 69, proteinPerGram: 0.4, fatPerGram: 0.1, fibersPerGram: 1.1),
  Food(id: '93', name: 'کیک یزدی', carboPerGram: 24.6, proteinPerGram: 4.1, fatPerGram: 14, fibersPerGram: 0.1),
  Food(id: '94', name: 'چیپس نمکی', carboPerGram: 54, proteinPerGram: 6.4, fatPerGram: 34, fibersPerGram: 3.1),
  Food(id: '95', name: 'پفک', carboPerGram: 53, proteinPerGram: 6, fatPerGram: 37, fibersPerGram: 1.7),
  Food(id: '96', name: 'شکلات تلخ (70%-85%)', carboPerGram: 46, proteinPerGram: 7.7, fatPerGram: 42.5, fibersPerGram: 11),
  Food(id: '97', name: 'سالاد فصل', carboPerGram: 4.8, proteinPerGram: 1, fatPerGram: 1.8, fibersPerGram: 1.3),
  Food(id: '126', name: 'بستنی سنتی', carboPerGram: 44.5, proteinPerGram: 3.2, fatPerGram: 7.1, fibersPerGram: 0.4),
  Food(id: '127', name: 'بستنی میوه‌ای', carboPerGram: 28, proteinPerGram: 3.2, fatPerGram: 8, fibersPerGram: 0.9),
  Food(id: '128', name: 'پسته (خام)', carboPerGram: 28, proteinPerGram: 20, fatPerGram: 45, fibersPerGram: 10),
  Food(id: '129', name: 'قارچ پلو', carboPerGram: 29.6, proteinPerGram: 3.5, fatPerGram: 5.9, fibersPerGram: 1.9),
  Food(id: '130', name: 'لوبیا پلو با گوشت', carboPerGram: 22.3, proteinPerGram: 4, fatPerGram: 6.3, fibersPerGram: 0.9),
  Food(id: '131', name: 'مرصع پلو', carboPerGram: 25, proteinPerGram: 11.3, fatPerGram: 11.8, fibersPerGram: 1.3)
  ];
  final drinks = [
  Food(id: '132', name: 'شیر پرچرب میهن', carboPerGram: 0, proteinPerGram: 3.2, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '133', name: 'شیر کم‌چرب میهن', carboPerGram: 0, proteinPerGram: 3.4, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '134', name: 'شیر کاکائو', carboPerGram: 10, proteinPerGram: 3.2, fatPerGram: 3.4, fibersPerGram: 0.8),
  Food(id: '135', name: 'نوشابه گازدار', carboPerGram: 9, proteinPerGram: 0, fatPerGram: 0, fibersPerGram: 0),
  Food(id: '136', name: 'آب سیب', carboPerGram: 11, proteinPerGram: 0.1, fatPerGram: 0.1, fibersPerGram: 0.2),
  Food(id: '100', name: 'آب هویج', carboPerGram: 9, proteinPerGram: 1, fatPerGram: 0.2, fibersPerGram: 0.8),
];



